/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pair`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contents`; params?: Router.UnknownInputParams; } | { pathname: `/devices`; params?: Router.UnknownInputParams; } | { pathname: `/feeds`; params?: Router.UnknownInputParams; } | { pathname: `/groups`; params?: Router.UnknownInputParams; } | { pathname: `/moderation`; params?: Router.UnknownInputParams; } | { pathname: `/playlists`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/templates`; params?: Router.UnknownInputParams; } | { pathname: `/users`; params?: Router.UnknownInputParams; } | { pathname: `/devices/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screens/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pair`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/contents`; params?: Router.UnknownOutputParams; } | { pathname: `/devices`; params?: Router.UnknownOutputParams; } | { pathname: `/feeds`; params?: Router.UnknownOutputParams; } | { pathname: `/groups`; params?: Router.UnknownOutputParams; } | { pathname: `/moderation`; params?: Router.UnknownOutputParams; } | { pathname: `/playlists`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/templates`; params?: Router.UnknownOutputParams; } | { pathname: `/users`; params?: Router.UnknownOutputParams; } | { pathname: `/devices/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/screens/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/pair${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/contents${`?${string}` | `#${string}` | ''}` | `/devices${`?${string}` | `#${string}` | ''}` | `/feeds${`?${string}` | `#${string}` | ''}` | `/groups${`?${string}` | `#${string}` | ''}` | `/moderation${`?${string}` | `#${string}` | ''}` | `/playlists${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/templates${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pair`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/contents`; params?: Router.UnknownInputParams; } | { pathname: `/devices`; params?: Router.UnknownInputParams; } | { pathname: `/feeds`; params?: Router.UnknownInputParams; } | { pathname: `/groups`; params?: Router.UnknownInputParams; } | { pathname: `/moderation`; params?: Router.UnknownInputParams; } | { pathname: `/playlists`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/templates`; params?: Router.UnknownInputParams; } | { pathname: `/users`; params?: Router.UnknownInputParams; } | `/devices/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/screens/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/devices/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screens/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
